### ISSUE TITLE
Fix po number recording

### ISSUE THREAD

**Issue by PaulEllis2001** [cs481-ekh/s23-totalled#118]
The senior design po number is currently not recorded into the line item so it needs to be recorded for the expense breakdown.
This includes:
 - [ ] Update LineItem to contain a new field
 - [ ] Update SheetToTeamParser to put the "senior design po" column into the line item

**Comment by BreeLatimer** [comment]
May I suggest that we add on to this task tracking for both `PO` and `Project Name`? We have Team name, but we do not have any way for the project name to be passed in yet :)

**Comment by PaulEllis2001** [comment]
Project name will be team based not LineItem based, it is also part of the stretch goal I believe. For now I would just use the team name as the project name as I have no integration with D's Project Book Parsing. Changing this can be a task for the next sprint

**Comment by PaulEllis2001** [comment]
{t:15}
