### ISSUE TITLE
Create GitHub Page

### ISSUE THREAD

**Issue by BreeLatimer** [cs481-ekh/s23-totalled#126]
We need to create the GitHub Page in order to meet the requirements for that assignment. 

According to the assignment we need to have:

- Project title
- Team Members
- Project abstract
  - Start with your project statement
  - Should be concise (~200 words)
  - Descriptive enough for someone outside to understand
- Project Description
  - Describe what you actually built
  - How it works
  - Screenshots

We can use a GitHub Page template in order to have a clean looking site. Here is an example for what our website should roughly look like: https://cs481-ekh.github.io/s21-team-blue/

**Comment by ChaseStauts** [comment]
Had issues with image loading in the markup syntax in addition to ability add newlines
{t:180}
