### ISSUE TITLE
Testing Framework setup and stubbing

### ISSUE THREAD

**Issue by PaulEllis2001** [cs481-ekh/s23-totalled#13]

**Comment by BreeLatimer** [comment]
- Started researching how to implement JUnit
- Began work on writing a starter test class
- Began implementing JUnit. More work is needed.

{t:54}

**Comment by BreeLatimer** [comment]
- Got JUnit implemented
 - Worked through a bit of debugging why the program wasn't building
 - Added a quick sample test to show what a passing test should look like

{t:105}
