### ISSUE TITLE
Each Team will have their Team Expense Breakdown written to a File

### ISSUE THREAD

**Issue by PaulEllis2001** [cs481-ekh/s23-totalled#49]
- [ ] The program will pass Apache POI a location to save the file and Apache POI will attempt to open a writable file for each team at the location
 - [ ] Apache POI will write out data passed by the program to the files
 - [ ] Apache POI will close the files and return a success message to the UI

**Comment by BreeLatimer** [comment]
- Implementing code
{t:90}

**Comment by BreeLatimer** [comment]
- Pull request review and merge
{t:15}
