### ISSUE TITLE
Set Up CI

### ISSUE THREAD

**Issue by PaulEllis2001** [cs481-ekh/s23-totalled#9]
As a developer, I need to introduce continuous integration in order to keep our product updated and reduce the time between updates and deployments

- [x] Need to create CI.yml in .github repository to run general continuous integration functionality
- [x] Need to integrate build.sh script to deploy our product
- [x] Need to integrate test.sh script to run our junit tests
- [ ] Integrate docker

**Comment by ChaseStauts** [comment]
Worked on adding continuous integration support integration with github actions via the ci.yml file. Created the first iteration of the CI and may need further adaptations in the future. {t:60}
